server:
  port: 8310

spring:
  application:
    name: consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8761/eureka/,http://user:123456@peer2:8762/eureka/
