spring:
  application:
    name: eureka-application
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka_peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka_peer2