server:
  port: 8901
spring:
  application:
    name: hystrix-turbine-server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
turbine:
  # 要监控的微服务列表，多个用,分隔
  appConfig: PROVIDER-USER,CONSUMER-MOVIE-FEIGN-WITH-HYSTRIX
  clusterNameExpression: "'default'"