server:
  port: 8903
spring:
  application:
    name: gateway-zuul-filter
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix: DEBUG
zuul:
  routes:
    user-route: # 该配置方式中，user-route只是给路由一个名称，可以任意起名
      service-id: provider-user
      path: /user1/**
    provider-user: /user2/** # 调用地址为 http://localhost:8902/user/users/1
  # ignored-services: provider-user # 这里可以写'*'来忽略所有路由，仅开放指定路由
  # ignored-patterns: /**/users/1 # 忽略带有该路径的访问

